### ISSUE TITLE
Dynamic Port configuration

### ISSUE THREAD

**Issue by HaloX69** [PowerShell/xSqlPs#22]
If you do not provide the Port number attribute it should leave that out of the registry entry which would indicate dynamic port selection, but instead the registry key is created with a zero port number.  We cannot have a zero port number so it should test if its other than zero to append it to the key value.  This would also mean that this logic would need to be implemented in the test as well.

**Comment by kwirkykat** [comment]
@HaloX69 Closing all issues in this repository as it has been deprecated since all the functionality is covered much better by [xSqlServer](https://github.com/PowerShell/xSqlServer).
