### ISSUE TITLE
xSqlServerInstall does not work with SQL Server 2014

### ISSUE THREAD

**Issue by allansson** [PowerShell/xSqlPs#6]
When trying to use the xSqlServerInstall-resource to install SQL Server 2014, the resource fails with the following message:

```
==> default: PowerShell DSC resource MSFT_xSqlServerInstall failed to execute Set-TargetRes 
==> default: ource functionality with error message: SQL Server installation did not succeed 
==> default: . For more details please refer to the logs under C:\Program Files\Microsoft SQ 
==> default: L Server\110\Setup Bootstrap\Log folder. 
```

The issue is caused by this [line](https://github.com/PowerShell/xSqlPs/blob/dev/DSCResources/MSFT_xSqlServerInstall/MSFT_xSqlServerInstall.psm1#L154):

``` powershell
$LogPath = Join-Path $env:ProgramFiles "Microsoft SQL Server\110\Setup Bootstrap\Log"   
```

The resource cannot find the summary.txt file, because the installer for SQL Server 2014 puts its log in the directory "Microsoft SQL Server\120".

**Comment by Matticusau** [comment]
I've got a fix for this in my branch but am waiting for it to be pulled back into the main branch. My fix allows this to support any version with 2014 being the default (although that will have to change soon)

**Comment by nebffa** [comment]
It's been a while @Matticusau - should you raise a pull-request?

**Comment by Matticusau** [comment]
My fix for this was pulled into the Dev branch in Pull Request commit [97d0522](https://github.com/PowerShell/xSqlPs/commit/97d05228eb7a8cd8abb996cd2732a755fdfc0042)
Or you can go download mlSqlPs from here or PowerShell Gallery for the same and tested code

**Comment by Bjorn80** [comment]
Hi
When installing Sql 2014 with the binaries on a share i get:
`VERBOSE: [SQL]:                            [[xSqlServerInstall]installSqlServer] NetUse set share \\shareserver\SQL2014\ ...
System error 53 has occurred.
    + CategoryInfo          : NotSpecified: (System error 53 has occurred.:) [], CimException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : localhost

The network path was not found.
VERBOSE: [SQL]:                            [[xSqlServerInstall]installSqlServer] Validating access to \\shareserver\SQL2014\
Access is denied
    + CategoryInfo          : PermissionDenied: (\\shareserver\SQL2014\:) [], CimException
    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.TestPathCommand
    + PSComputerName        : localhost

VERBOSE: [SQL]: LCM:  [ End    Set      ]  [[xSqlServerInstall]installSqlServer]  in 0.2660 seconds.
PowerShell DSC resource MSFT_xSqlServerInstall  failed to execute Set-TargetResource functionality with error message: SQL Server install media path was not found. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost 
`

There shouldnt be any issues that sql binaries are on a unc path? Or any clues to what i am doing wrong?


brgs

Bjørn

**Comment by ghost** [comment]
@Matticusau
The xSqlps is still outdated or has been updated?

Im getting te same fault using it:
`PowerShell DSC resource MSFT_xSqlServerInstall  failed to execute Set-TargetResource functionality with error message: SQL Server installation did not succeed. For more details please refer to the logs under C
:\Program Files\Microsoft SQL Server\120\Setup Bootstrap\Log folder. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [TIW0KOSS-SQL01]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 34.389 seconds 
`

**Comment by dgarc23** [comment]
Im getting the same... as @Bjorn80 SQL Server is installed, but something is not okay... seems like the last configuration is not working...
So any updates on this? Should I use it even if its not finishing correctly?  Whats the impact?

**Comment by ghost** [comment]
dgarc23

Try the xsqlserver module instead. Worked like a charm for me.
https://github.com/PowerShell/xSQLServer

brgs

Bjørn

**Comment by dgarc23** [comment]
working on that... will try today and let you know later... thanks @Bjorn80

**Comment by dgarc23** [comment]
I had the problem that, for the SQL Installer, it always add a folder named “source” in the path…
I was mounting an iso file, so I don’t like that.  I had to extract the installer files, but to copy those files or extract, takes much longer than only mount the iso…
So I don’t like that… but it seems to be working fine…

Daniel

**Comment by Matticusau** [comment]
It probably isnt anything specific about xsqlps vs xsqlserver as both just do unattended installs of sql server using setup.exe.
What you need to do is check the setup log files. Usually found in c:\program files\microsoft sql server###\setup bootstrap\logs.... (from memory as im on mobile). Where the ### is the numeric code for the version (ie 120 for sql 2014).
While setup.exe may have finished it may not have installed everything 100%. But that log should tell u.
After that the next step is to check the ERRORLOG file in the log directory of the instance. That will tell u abourt issues the instance is having starting or at runtime.
On this note, Do you think this type of troubleshootingtips would be worth documenting in a troubleshooting.md guide file or something? I recognize that not everyone that uses these resources are going to be familar with troubleshooting sql issues. Im already planning to work on a guide but just interested on ur thoughts.
Matt<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: dgarc23 notifications@github.com </div><div>Date: 11/05/2016  5:04 AM  (GMT+10:00) </div><div>To: PowerShell/xSqlPs xSqlPs@noreply.github.com </div><div>Cc: Matt matt.lavery@outlook.com, Mention mention@noreply.github.com </div><div>Subject: Re: [PowerShell/xSqlPs] xSqlServerInstall does not work with SQL Server 2014 (#6) </div><div>
</div>
I had the problem that, for the SQL Installer, it always add a folder named “source” in the path…
I was mounting an iso file, so I don’t like that.  I had to extract the installer files, but to copy those files or extract, takes much longer than only mount the iso…
So I don’t like that… but it seems to be working fine…

Daniel
